export const AllBetsData = [

    {
        "id": 1,
        "game": "Mines",
        "player": "rex***084",
        "bet": "11.01",
        "multiplier": "5.00x",
        "payout": "$2.76",
    },
    {
        "id": 2,
        "game": "Kino",
        "player": "a15***xd5",
        "bet": "7.59",
        "multiplier": "1.00x",
        "payout": "$7.38",
    },
    {
        "id": 3,
        "game": "Baccarat",
        "player": "lin***n18",
        "bet": "5.45",
        "multiplier": "3.07x",
        "payout": "$0.89",
    },
    {
        "id": 4,
        "game": "Plinko",
        "player": "lud***069",
        "bet": "4.01",
        "multiplier": "7.10x",
        "payout": "$2.23",
    },
    {
        "id": 5,
        "game": "Crash",
        "player": "ian***014",
        "bet": "14.08",
        "multiplier": "22.19x",
        "payout": "$23.69",
    },
    {
        "id": 6,
        "game": "Double",
        "player": "luz***110",
        "bet": "30.36",
        "multiplier": "14.01x",
        "payout": "$00.00",
    },
    {
        "id": 7,
        "game": "Hilo",
        "player": "bax***041",
        "bet": "04.50",
        "multiplier": "5.00x",
        "payout": "$25.45",
    },
    {
        "id": 8,
        "game": "Coin",
        "player": "hey***045",
        "bet": "65.01",
        "multiplier": "1.89x",
        "payout": "$45.00",
    },
    {
        "id": 9,
        "game": "Limbo",
        "player": "don***fty",
        "bet": "04.78",
        "multiplier": "8.00x",
        "payout": "$00.00",
    },
    {
        "id": 10,
        "game": "Tower",
        "player": "emz***bjk",
        "bet": "69.00",
        "multiplier": "69.15x",
        "payout": "$78.50",
    },
    {
        "id": 11,
        "game": "Coin",
        "player": "srp***nnb",
        "bet": "10.41",
        "multiplier": "78.52x",
        "payout": "$00.00",
    },
    {
        "id": 12,
        "game": "Crash",
        "player": "ian***014",
        "bet": "14.08",
        "multiplier": "22.19x",
        "payout": "$23.69",
    },
    {
        "id": 13,
        "game": "Double",
        "player": "luz***110",
        "bet": "30.36",
        "multiplier": "14.01x",
        "payout": "$00.00",
    },
    {
        "id": 14,
        "game": "Hilo",
        "player": "bax***041",
        "bet": "04.50",
        "multiplier": "5.00x",
        "payout": "$25.45",
    },
    {
        "id": 15,
        "game": "Baccarat",
        "player": "lin***n18",
        "bet": "5.45",
        "multiplier": "3.07x",
        "payout": "$0.89",
    },

]